### ISSUE TITLE
Need Playground / Demo Page

### ISSUE THREAD

**Issue by JMichaelTX** [turnermm/sectiontoggle#14]
Hi, your plugin sounds great, but I really need to be able to test it before I install it.
Do you have a DokuWiki Playground page where it can be tested?

Thanks.

**Comment by turnermm** [comment]
If you have a tablet you can see it working here:
   https://mturner.org/devel/doku.php

**Comment by thorus90** [comment]
As you cannot display the source there, this is useless. I can't get it to work either :/. And the documentation at https://www.dokuwiki.org/plugin:sectiontoggle explains very little.

**Comment by turnermm** [comment]
I don't understand this question.  If you need to see the source, then just look at the pluigin's code.
