### ISSUE TITLE
Can I have the first section opened by default?

### ISSUE THREAD

**Issue by jorbig** [turnermm/sectiontoggle#30]
I love this plugin! But is there a way to have the first section opened by default, instead of everything closed?

**Comment by turnermm** [comment]
I have been working on an update where clicking on an item in the table of content will open and close the section and where a link containing a section reference (i.e. a url hash: url#section_name) will automatically open the section when the page is loaded. I will see if I can fit this request into this upgrade.  The upgrade is https://github.com/turnermm/sectiontoggle/archive/skip.zip

**Comment by turnermm** [comment]
This is now done.  See the plugin page: https://www.dokuwiki.org/plugin:sectiontoggle#auto_toggling

**Comment by jorbig** [comment]
Awesome! Thank you very much for this great feature!

Op wo 6 mei 2020 om 15:42 schreef Myron Turner <notifications@github.com>:
