### ISSUE TITLE
FEATURE REQUEST: add parameter to heading to not collapse

### ISSUE THREAD

**Issue by lizat** [turnermm/sectiontoggle#31]
Hello Myron,

This may be impossible but in case it isn't and others are interested I am logging this request here.

I would like to be able to override the section toggle on occasion. it is usually when linking to a section. So it is OK to be collapsed in normal circumstances but when using a link to the section I would like to override the rule. Something like this would be good:

 [[process:1110_manage_people:1102_search#search_type|[1102] Search for Item - Search Type &expand]] 

I have no idea if this is even feasible - passing a parameter with a link? 
The origin of the request is that if I am directing the reader to a particular section using a link it seems rather unfriendly if the section is (correctly) collapsed.

Thank you for anther useful plugin!

**Comment by turnermm** [comment]
This is now done. See the plugin page: https://www.dokuwiki.org/plugin:sectiontoggle#auto_toggling
