### ISSUE TITLE
Some cases when folding doesn't work

### ISSUE THREAD

**Issue by astroHaoPeng** [turnermm/sectiontoggle#34]
When you have headlines with no content directly after it, folding is incorrect. For example, it doesn't fold at `2nd`, `3rd`, but folds at `4th` for the following case：
```
====== 1st (pagetitle, set for no folding) ======
Text
===== 2nd ===== 
(Blank)
==== 3rd ====
(Blank)
=== 4th ===
Text.
```

When you have specific characters in headline, it stops folding correctly. For example below, the plus sign in `C++` makes everything after it stop folding:
```
====== 1st (pagetitle, set for no folding) ======
Text
===== 2nd ===== 
Text
==== 3rd (Python) ====
Text
==== 3rd (Cpp) ====
Text
==== 3rd (C++) ====
Text
==== 3rd (Fortran) ====
Text
==== 3rd (MATLAB) ====
Text
```

![image](https://user-images.githubusercontent.com/7337114/102435521-c11e1680-3fe4-11eb-97ec-a461bfb5690a.png)

**Comment by turnermm** [comment]
It is designed not to fold where there is no content under the heading.

**Comment by turnermm** [comment]
The second issue, where the headers do not collapse after certain characters is now fixed.  Thanks for pointing this out.

**Comment by astroHaoPeng** [comment]
Nice job! Cool!
