### ISSUE TITLE
Use it with dokubook ?

### ISSUE THREAD

**Issue by Helianza** [turnermm/sectiontoggle#38]
Hello,

I installed the plugin, and it works with dokuwiki templates. 
How can I use it with dokubook ? I find about the id or div conf, but I don't know what to put in it.

Can you help me ?
Thanks a lot !

Damien

**Comment by turnermm** [comment]
The plugin has not been set up for use with dokubook.

**Comment by Helianza** [comment]
Sad !
And do you if another plugin exists to do something like that for this template ? (I ask, to know, but I understand it's not your area)

**Comment by Helianza** [comment]
I update the dokubook template, and it is now working perfectly !
