### ISSUE TITLE
Update for "sectiontoggle Plugin" for dokuwiki did not work

### ISSUE THREAD

**Issue by update-freak** [turnermm/sectiontoggle#44]
I saw that there is an update for the Plugin "sectiontoggle" for DokuWiki (https://www.dokuwiki.org/plugin:sectiontoggle).
After updating the extension there is still the message that the plugin is not up-to-date and there is an update available (see screenshot).
I also tried to reinstall the plugin, but that also did not work.

![2023-12-31 11_14_34-Erweiterungen verwalten  DokuWiki](https://github.com/turnermm/sectiontoggle/assets/40196995/1fdc2d25-cbd2-4c2d-9c07-d861f3bf7478)

**Comment by Elbie-em** [comment]
@update-freak this issue has been resolved. You can click update and that message should go away.

**Comment by update-freak** [comment]
Yes, click on "update" solved the issue.
Thank you very much!
