### ISSUE TITLE
does not work with "writr" template?

### ISSUE THREAD

**Issue by rwoldu** [turnermm/sectiontoggle#7]
Hi,
great plugin! I've tested it with the standard dokuwiki-template, and it worked! But with the writr-template it doesn't...Do I have to adjust the config (maybe to "id" or "class")?

Thanks in advance!

**Comment by turnermm** [comment]
It has to be configured for templates other than the dokuwiki.  See: https://www.dokuwiki.org/plugin:sectiontoggle#configuration and the [[example]](https://www.dokuwiki.org/plugin:sectiontoggle#example).

**Comment by rwoldu** [comment]
Wow, that was fast ;)
Thanks!
