### ISSUE TITLE
Plugins does not work on detritus

### ISSUE THREAD

**Issue by impactJL** [turnermm/sectiontoggle#8]
Hello
here are the steps :
1I have the detritus version
2i use the dokuwiki template
3i have installed the plugins
4the installation works well
5 when i put this in my code " stoggle_buttons" with the "~~" as asked in the documentation page, i get the buttons, but i do not get the toggle on the href title. If i click on one the two buttons, nothing happens.
Could you help me to fix this problem ?
Regards

**Comment by turnermm** [comment]
It's probably a caching problem.  So, re-open the page, type something into it, and save it. You can then open and delete the temporary entry. Here is an example page using Detritus and the two toggle buttons:
http://www.mturner.org/devel/events/event_handlers

It works on both my Ipad and my Blackberry phone.
http://www.mturner.org/devel/events/event_handlers

**Comment by impactJL** [comment]
Hello
thank you very much for your prompt help.
Unfortunately it still doesn't work
When i go there : http://www.mturner.org/devel/events/event_handlers i got the toggle.
exept puttin " stoggle_buttons" should did i forgot some steps ?

regards

**Comment by turnermm** [comment]
Do you have a public wiki that I can see online?

**Comment by impactJL** [comment]
Yes 
here is a very basic example :
http://158.255.99.187/dokuwiki/doku.php?id=wiki:testtoggle

**Comment by turnermm** [comment]
As far as I can tell from checking the javascript, the sectiontoggle plugin is not loaded.  Also, your installation appears to be incomplete.

**Comment by impactJL** [comment]
Hello
thank you for this return
when i check the plugin manager it's loaded.
I re-install it and it seems that the installation is successful since i got this : "Plugin sectiontoggle updated successfully"

I the plugin manager it seems to be ok : 

Status:
    installed, enabled, plugin
Download URL:
    github.com/turnermm/sectiontoggle/archive/master.zip
Repository:
    github.com/turnermm/sectiontoggle
Installed version:
    2015-02-16
Your last update:
    Mon, 02 Nov 2015 06:34:43 -0800
Provides:
    Syntax
Compatible with:
    "Hrun" (2014-09-29), "Weatherwax" (2013-05-10), "Adora Belle" (2012-10-13)

What i can not understand is that i can get the default toggle for the table of content, but not for the rest of the article.
Do you have any idea of what i can do ?

Thank in advance

**Comment by turnermm** [comment]
> What i can not understand is that i can get the default toggle for the table of content, but not for the rest of the article.
I don't understand what this means.  And when I checked the javascript for the web site I did not find any references to the sectiontoggle plugin.

**Comment by impactJL** [comment]
What i wanted to say is that i can see a toggle, the one used by the template for the toc. Is is not related to the sectiontoggle plugin.

if there is issues concerning the loading, how can i force the loading directly in the page ?
regards

**Comment by impactJL** [comment]
Hello
it works !
in fact i didn't use the right way to clear the cache
Here is what solved my issue :+1: 
clear DokuWikis cache in order to make this plugin working. Otherwise it won't fold/unfold correctly. To clear the cache open → modify any character → undo → save → close the file <YourDokuWikiRoot>/conf/local.php. This causes DokuWiki to rebuild it's cache

Hope it will help

thank again for helping me

regards

**Comment by turnermm** [comment]
>  What i wanted to say is that i can see a toggle, the one used by the template for the toc. Is is not related to the sectiontoggle plugin.

No, it's not.  And why its hot loading, I can't say.

**Comment by turnermm** [comment]
On 11/2/2015 9:27 AM, impactJL wrote:
> o clear the cache open → modify any character → undo → save → close the
> file /conf/local.php. This causes DokuWiki to rebuild it's cache

Which is what I said to begin with.

-- 
Myron Turner
http://mturner.org/
https://github.com/turnermm

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by impactJL** [comment]
Yes indeed you mentionned this caching issue. I thought i need to reload the edited page, not the local.php 
anyway it works now
thanks for you help
